### ISSUE TITLE
export use_directory()

### ISSUE THREAD

**Issue by s-fleck** [r-lib/usethis#27]
Could you please export `use_directory()`? I know that its pretty simple, but useful if you want to create your own `use_*` functions. If you decide that that this is a good idea, I can write the roxygen for it.

**Comment by hadley** [comment]
Are you still interested in this? A PR would be great.

**Comment by s-fleck** [comment]
submitted a pull request

**Comment by s-fleck** [comment]
Sorry for forgetting to document path; hope everything is fixed now

**Comment by hadley** [comment]
I think you forgot to push or otherwise update the PR - #44 hasn't changed
